export const products = [
    {
        id: '1',
        category: 'muebles',
        name: 'Mesa Comedor',
        price: 300,
        description: 'Una elegante mesa de comedor de madera.',
        img: 'muebles.jpg',
    },
    {
        id: '2',
        category: 'muebles',
        name: 'Placard',
        price: 500,
        description: 'Espacioso placard multiespacio',
        img: 'muebles2.jpg',
    },
    {
        id: '3',
        category: 'muebles',
        name: 'Sillon Cama',
        price: 350,
        description: 'Un clasico sillón de madera con una cama desplegable',
        img: 'muebles3.jpg',
    },
    {
        id: '4',
        category: 'interior',
        name: 'Mesa Living',
        price: 300,
        description: 'Mesa circular, ideal para cualquier living',
        img: 'interior.jpg',
    },
    {
        id: '5',
        category: 'interior',
        name: 'Espejo de pared',
        price: 250,
        description: 'Espejo de sol, para la pared de tu living',
        img: 'interior3.jpg',
    },
    {
        id: '6',
        category: 'exterior',
        name: 'Mesa y sillones de jardín',
        price: 700,
        description: 'Juego de mesa y sillones para tu jardín',
        img: 'exterior.jpg',
    },
    {
        id: '7',
        category: 'exterior',
        name: 'Sillones y mesa de jardín',
        price: 700,
        description: 'Dos Sillones Acapulco para jardín, con una mesa de vidrio',
        img: 'exterior2.jpg',
    },
    {
        id: '8',
        category: 'exterior',
        name: 'Silla Colgante',
        price: 500,
        description: 'Hamaca Colgante tailandesa para jardín o balcón',
        img: 'exterior3.jpg',
    }
]